CREATE TABLE Servers (
    id TEXT PRIMARY KEY,
    serverName TEXT NOT NULL,
    serverIconURL TEXT,
    serverIconData BLOB,
    created TIMESTAMP DEFAULT NULL,
    archived TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(id)
);